### ISSUE TITLE
Bug al querer modificar / eliminar un grupo

### ISSUE THREAD

**Issue by ramiroyep** [tferraro/tacs#128]
No se puede hacer 2 acciones seguidas sobre el mismo grupo. Dsp de crearlo, no se puede modificarlo o borrarlo... Si uno cambia de pestaña (por ejemplo, a personajes) y vuelve, sí puede realizar las acciones...

**Comment by sebassco-dp** [comment]
Esto quedo resuelto por #26. Closing.
