### ISSUE TITLE
Headers: Inyección sobre respuestas

### ISSUE THREAD

**Issue by sebassco-dp** [tferraro/tacs#13]
Deberíamos tener en cuenta lo que dice el RFC sobre las respuestas? Porque en ese caso, deberíamos pensar en la espera o devolución de algunos headers, y estaría bueno que lo especifiquemos. Una vez que tengamos esto aclarado, me pongo manos a la obra.

**Comment by tferraro** [comment]
:+1: , no realicé una especificación de la response completa porque era más bien un borrador, pero si, debería devolver un header con más información del status.

**Comment by sebassco-dp** [comment]
Listo. Tom, hablemos mañana sobre el cacheo please. Solo para tenerlo en cuenta.
Abrazo!
