### ISSUE TITLE
Levantar la base de Angular en el proyecto

### ISSUE THREAD

**Issue by tferraro** [tferraro/tacs#41]

**Comment by sebassco-dp** [comment]
@ezebsas tmb esta asignado

**Comment by tferraro** [comment]
Creé un [gist](https://gist.github.com/tferraro/bb932be674e4c9ddf5dd80ee940019e6) con un poco de la info que uso en un proyecto que tiene angular. La idea es que usa un controller y un servicio comunes y despues cada recurso se amolda a usar esa base.
