### ISSUE TITLE
Cambiar el login

### ISSUE THREAD

**Issue by tferraro** [tferraro/tacs#66]
Sacar el header de angular y ponerlo en, no se, alguna cookie? O algo que no se vaya si haces refresh...

**Comment by fabidelacruz** [comment]
En el branch en el que estoy trabajando tengo agregado localStorage (o
cookies si no es compatible con el primero). Podemos agregarlo ahi

2016-06-12 13:29 GMT-03:00 Tomás Ferraro <notifications@github.com>:

**Comment by tferraro** [comment]
Piola!!

**Comment by sebassco-dp** [comment]
Ok, mañana lo agarro a menos que ya estén laburando con eso.

**Comment by fabidelacruz** [comment]
Ya lo tengo pusheado en el branch dev_user

2016-06-12 22:47 GMT-03:00 Sebastián Gómez Battista <
notifications@github.com>:

**Comment by sebassco-dp** [comment]
Oka!

**Comment by sebassco-dp** [comment]
Cerrado por @fabidelacruz !
