### ISSUE TITLE
Timeout del get a Marvel

### ISSUE THREAD

**Issue by tferraro** [tferraro/tacs#72]
Hay que actualizar la base de personajes del sistema cada X tiempo (calculemoslo por los querys que nos dan, pongamosle cada día o menos).

Al hacerlo así, te aseguras que existan cambios y nuevos personajes sin drama, ya que el frontend pega siempre conta el "get" general. Buscar por id particular es un NO, ya que no lo tenemos. Buscar por nombre se puede. La fulera de ambas es que pegandote contra nombres chamullos te matan las querys contra marvel y no queremos eso :P. Por lo tanto, @fabidelacruz tiro la opción de arriba que queda mucho más limpia.

**Comment by tferraro** [comment]
PR is #104

**Comment by fabidelacruz** [comment]
Closed #104
