### ISSUE TITLE
Agregar diferenciación de respuestas segun el rol

### ISSUE THREAD

**Issue by tferraro** [tferraro/tacs#97]
Esto iría en el backend no? Según si es user o admin le da solo las que le corresponden.

**Comment by tferraro** [comment]
Los que aplican:

- GET /users y /users/id, si el usuario es solamente un usuario admin ta piola, si es un user solo devuelve una lista con el mismo, o al el mismo, en el caso de que no sea él mismo, Forbbiden.
- ANY /user/id que no sea admin o el propio usuario, te la hace comer con un Forbbiden. MENO el DELETE, un user no se puede eliminar a si mismo.
- GET /groups no está muy claro en el enunciado. Tomemos como que un user comun NO puede ver los grupos de otro user.
- ANY /group/id que no sea admin o el usuario creador, te la hace comer con un Forbbidden.

**Comment by tferraro** [comment]
Lo probé y no funciona :/

**Comment by sebassco-dp** [comment]
Cierro. Subo lo de grupos en el #26 .
